[build]
  base = "."
  command = "pip install -r backend/requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200

[functions]
  directory = "netlify/functions"
