[providers]
python = "3.11.0"

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Backend build complete'"]

[start]
cmd = "cd backend && python improved_main.py"
