[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python improved_main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.nixpacksConfig]
providers = ["python"]

[build.nixpacksConfig.variables]
PYTHON_VERSION = "3.11.0"
